language: python
python:
  - "nightly"
  - "3.7-dev"
  - 3.6
  - 3.5
  - 3.4
sudo: false
install:
  - |
    # pip install
    pip install --upgrade setuptools pip
    pip install --pre .
    pip install ipykernel[test] codecov
  - |
    # install matplotlib
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install matplotlib curio trio
    fi
  - |
    # pin tornado
    if [[ ! -z "$TORNADO" ]]; then
      pip install tornado=="$TORNADO"
    fi
  - pip freeze
script:
  - jupyter kernelspec list
  - pytest --cov ipykernel --durations 10 -v ipykernel
after_success:
  - codecov
matrix:
  include:
    - python: 3.5
      env:
        - TORNADO="4.5.*"
  allow_failures:
    - python: "nightly"
