language: python
python:
    - "nightly"
    - 3.6 
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install -f travis-wheels/wheelhouse --pre .
    - pip install -f travis-wheels/wheelhouse ipykernel[test] nose-timer
    - |
      if [[ "$TRAVIS_PYTHON_VERSION" != "3.3" ]]; then
        pip install matplotlib
      fi
script:
    - jupyter kernelspec list
    - nosetests --with-coverage --with-timer --cover-package ipykernel ipykernel
after_success:
    - codecov
matrix:
    allow_failures:
        - python: "nightly"
