language: python
python:
    - "nightly"
    - 3.6
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
install:
    - |
      pip install --upgrade setuptools pip
      pip install --pre .
      pip install ipykernel[test] codecov
    - |
      if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ||  "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        pip install matplotlib
      fi
script:
    - jupyter kernelspec list
    - pytest --cov ipykernel -v ipykernel
after_success:
    - codecov
matrix:
    allow_failures:
        - python: "nightly"
